stages:
  - build

build:
  tags:
    - shell
  stage: build
  script:
    - >
      if [ "$CI_COMMIT_REF_NAME" = "main" ]; then
        export DEPLOYMENT_TARGET="production"
      else
        export DEPLOYMENT_TARGET="development"
      fi
    - sh run.sh
